<a href="https://colab.research.google.com/github/Nisha-sah/Concepts-and-Technologies-of-AI/blob/main/Week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
empty_array = np.array((2, 2))
print("Empty Array (2x2):\n", empty_array, "\n")


import numpy as np
one_array = np.ones((4,2))
print(one_array)

import numpy as np
new_array = np.full((4,4),5, dtype=int)
print (new_array)


import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(arr)
print(zeros_like_array)

ones_like_array = np.ones_like(arr)
print("Ones Like Given Array:\n", ones_like_array, "\n")


new_list = [1,2,3,4]
array_from_list = np.array(new_list)
print("Array from list:\n", new_list )










Empty Array (2x2):
 [2 2] 

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[0 0 0]
 [0 0 0]]
Ones Like Given Array:
 [[1 1 1]
 [1 1 1]] 

Array from list:
 [1, 2, 3, 4]


In [ ]:
import numpy as np
array = np.arange(10, 50)
print("Array with values from 10 to 49:\n", array)


array = np.arange(9)

matrix_3x3 = array.reshape(3, 3)


print(matrix_3x3)

identity_matrix = np.eye(3)
print ("identity matrix:\n", identity_matrix )

random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array\n",random_array )
print("Mean value\n",mean_value)




random_array = np.random.random((10, 10))
print("Min:", random_array.min())
print("Max:", random_array.max())


arr_zeros = np.zeros(10)
arr_zeros[4] = 1

print("zero array\n", arr_zeros)



arr_reverse = np.array([1,2,0,0,4,0])
reverse_array = arr_reverse[::-1]
print("Reverse\n",arr_reverse)

array =np.ones((4,4));
array[1:-1, 1:-1]= 0;

print("2D array\n", array);


checkerboard = np.ones(8,8);
array[]







Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Array
 [0.45102366 0.98391588 0.34606198 0.04313203 0.58962377 0.98253009
 0.46906762 0.59214978 0.62950614 0.19513799 0.57604975 0.47930806
 0.8288352  0.26866829 0.72348261 0.66381299 0.32719053 0.47829653
 0.77132266 0.97015387 0.13993313 0.61168157 0.0168304  0.46728365
 0.9388647  0.63306542 0.99330275 0.83151439 0.55353414 0.64740113]
Mean value
 0.5734226900074623
Min: 0.0023681460941011867
Max: 0.9938763702422563
zero array
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reverse
 [1 2 0 0 4 0]
2D array
 [[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

print("Add:\n", x + y)
print("Sub:\n", x - y)
mul_x = x * 3
print("Multiply x by 3:\n", mul_x)

square_x = np.power(x,2)
print("square\n",square_x)

v = np.array([1, 2, 3])
w = np.array([4, 5, 6])
x = np.array([7, 8, 9])

# v.w
dot_vw = np.dot(v, w)
print("Dot product v·w:", dot_vw)

# x.v
dot_xv = np.dot(x, v)
print("Dot product x·v:", dot_xv)


x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

xy_row = np.concatenate((x, y), axis=0)
print("Concate:",xy_row)

Add:
 [[ 6  8]
 [10 13]]
Sub:
 [[-4 -4]
 [-4 -3]]
Multiply x by 3:
 [[ 3  6]
 [ 9 15]]
square
 [[ 1  4]
 [ 9 25]]
Dot product v·w: 32
Dot product x·v: 50
[[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]]);

A_inv = np.linalg.inv(A)
print("A inverse:\n", A_inv)

Ide = np.dot(A, A_inv)
print("A * A_inv =\n", Ide)


AB = np.dot(A,B)
print("AB doesnot equal to BA\n", AB)

BA = np.dot(B,A)
print("BA doesnot equal to AB\n", BA)


LHS = np.transpose(AB)
print("LHS\n", LHS)

RHS = np.dot(np.transpose(B), np.transpose(A))
print("RHS\n", RHS)

A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A * A_inv =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB doesnot equal to BA
 [[23 13]
 [51 29]]
BA doesnot equal to AB
 [[36 44]
 [13 16]]
LHS
 [[23 51]
 [13 29]]
RHS
 [[23 51]
 [13 29]]


In [ ]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])


A_inv = np.linalg.inv(A)


X = np.dot(A_inv, B)

print("Solution X =\n", X)


Solution X =
 [ 2.  1. -2.]
